name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Tests
      run: |
        python manage.py DS1Project/App/appmanager/tests.py

 
    - name: Run Docker Compose
      run: |
        docker-compose -f DS1Project/App/docker-compose.yml
    
 
